name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - ".github/workflows/main.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - ".github/workflows/main.yml"
  release:
    types:
      - published

env:
  REGISTRY: europe-north1-docker.pkg.dev/artifact-registry-5n/dapla-lab-docker
  IMAGE: onyxia-janitor

jobs:
  docker:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: "projects/848539402404/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
          service_account: "gh-actions-dapla-lab@artifact-registry-5n.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCP Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Determine Image Tag
        id: set-tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            echo "TAG=${TAG}" >> $GITHUB_ENV
            echo "tag=${TAG}" >> $GITHUB_OUTPUT
            echo "RELEASE_BUILD=true" >> $GITHUB_ENV
          else
            echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "RELEASE_BUILD=false" >> $GITHUB_ENV
          fi
          echo "Final image tag: ${TAG}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ steps.set-tag.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest